.github/workflows/build.yml
CMakeLists.txt
README.md

Qt5_DIR is the built-in way to find Qt's cmake files, so we can avoid the extra non-standard code
Also fixes some formatting & removes debug "echo" from actions file
Fixes #3

{cmake} Clarify finding of Qt

---

.github/workflows/build.yml

Setting "--parallel" on cmake uses CMAKE_BUILD_PARALLEL_LEVEL to determine number of jobs.
Could get fancy to determine number of cores but it's complicated with setting env vars between shells, so go for simplicity.

{cmake} Set CMAKE_BUILD_PARALLEL_LEVEL on Windows

---

include/GenericProgressCallback.h
src/NormalizedProgress.cpp

- replaces Qt code with the standard library
- if compiling without Qt, makes the counter thread-safe
Fixes #12

Replace QAtomicInt (and fake QAtomicInt) with std::atomic_uint

---

include/Delaunay2dMesh.h
include/Neighbourhood.h
include/PointProjectionTools.h
src/Delaunay2dMesh.cpp
src/LocalModel.cpp
src/Neighbourhood.cpp
src/PointProjectionTools.cpp

- use std::string instead of char * (fixes #27)
- move enum into namespace
- remove default arguments
- give names to some arguments (DUPLICATE_VERTICES, DO_NOT_DUPLICATE_VERTICES instead of true/false) so it's easier to read when used

Cleanup some function signatures

---

CMakeLists.txt

Ubuntu 19.x includes files for both CONFIG (TBBMakeConfig.cmake) and MODULE (FindTBB.cmake) style find_package. We need to force CONFIG because that is the style we are expecting.
Related #2
Fixes #33

{cmake} Fixes TBB linking on Ubuntu 19.x

---

src/AutoSegmentationTools.cpp

If AutoSegmentationTools::extractConnectedComponents ran out of memory, the memory wasn't freed properly.
Also convert to range-for loops for readability.

Fix potential mem leak in AutoSegmentationTools

---

include/GenericCloud.h
include/PointCloudTpl.h
src/AutoSegmentationTools.cpp
src/ScalarFieldTools.cpp
src/StatisticalTestingTools.cpp

Scalar field is either reserved or resized depending on whether the cloud is already populated or not)

Making the GenericCloud::enableScalarField method smarter

---

include/PointCloudTpl.h

I have experienced a number of segfaults and undefined behavior when working with scalar fields added to point clouds. Here are two minimum working examples:
```c++
int main(int argc, char** argv)
{
{
// Create a cloud with some points and a scalar field
CCCoreLib::PointCloud cloud_1;
cloud_1.resize(100);
sf_idx = cloud_1.addScalarField("test");
// Copying the cloud copies the pointer to the scalar field allocated by cloud_1, but it doesn't increment the field's link count
CCCoreLib::PointCloud cloud_2(cloud_1);
}
// When cloud_2 goes out of scope, the scalar field pointer is deleted
// Now, when cloud_1 goes out of scope it will also attempt to delete the pointer, resulting in a fault
}
```
```c++
int main(int argc, char** argv)
{
CCCoreLib::PointCloud cloud_2;
int sf_idx;
{
// Create a …
```

Fix shared scalar fields behavior

---

include/DgmOctree.h
src/DgmOctree.cpp

I have been attempting to use this library in a multi-threaded context and ran into issues with multiple threads reading/writing to various non-const static objects in the `DgmOctree` class that are used to facilitate it's own internal multi-threading. This PR moves those objects into the class to ensure that only one instance of the class in a single thread has access to them.
I believe there is a similar issue in `DistanceComputationTools` [here](https://github.com/CloudCompare/CCCoreLib/blob/61d69819765cd519a553994006ac9fb389ef1515/src/DistanceComputationTools.cpp#L1119), but it's not as simple to solve. Most of the methods that use objects are themselves static methods, meaning you couldn't move the objects into the `DistanceComputationTools` class and have those methods access them …

Octree multi-threading bug fix

---

include/GenericCloud.h
src/ScalarFieldTools.cpp
src/StatisticalTestingTools.cpp

They caused problems when generaring Doxygen's xml.

re-encore 3 files from windows codepage 1252 to utf-8

---

include/CMakeLists.txt

It was missing from the install list, so it gave an incomplete
installation
Fixes #72

Install CCMath.h file

---

include/PointCloudTpl.h

Fixes the Copyright sign © encoding.
Seems like I missed this in one my ealier attempts to fixes these.

PointCloudTpl.h Fix Copyright sign

---

include/CCPlatform.h

So that macOs builds of CloudCompare on Apple Silicon macs
properly shows 64 bits in its About Dialog & main window.

Add __arm64__ as a CC_ENV_64

---

CMakeLists.txt

For some reason cmake does not default to position-independent code for static library targets.
We ran into issues linking shared libraries with static CCCoreLib unless using -fPIC on Linux.

Build in -fPIC mode, even for static library.

---

CMakeLists.txt

* Move `tbb` version scheme from header to the cmake define.
* Explicate define targets as `tbb_imported_targets` was deprecated.

Fix tbb:2021 build

---

src/DgmOctree.cpp

I am not sure to understand why these processEvents calls freezes the ICP  on macOS...
Another possible fix is to set processCb=nullptr in ICPRegistrationTools::Register (thats why Registration worked when called from Python, with a null processCb).

fix the CloudCompare bug #1889 Registration tool broken, on macOS

---

include/CCPlatform.h

Required for ARM 64 bit builds to show up as 64 bit under Linux, as that uses `__aarch64__` instead of `__arm64__`.
Same spirit as 9f25a143791fef27d5b2989383fae26aa4c1513f.

Add __aarch64__ as a CC_ENV_64

---

include/ScalarField.h

emplace_back is unnecessary and prevents some optimizations

ScalarField: emplace_back -> push_back

---

include/ScalarField.h

Please see commits for details.

Scalar field improvements

---

include/Kriging.h
include/RayAndBox.h
include/ScalarFieldTools.h
src/AutoSegmentationTools.cpp
src/CCMiscTools.cpp
src/ChamferDistanceTransform.cpp
src/GridAndMeshIntersection.cpp
src/Kriging.cpp
src/LocalModel.cpp
src/ReferenceCloud.cpp
src/ScalarField.cpp

RayAnBox.h is missing the cassert header, but this issue is often overlooked because it is included after another header that already includes it.
This PR also fix non utf-8 chars in some files and remove unneeded header inclusions.

Missing assert header in RayAndBox.h 
